language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6-dev"
- "3.7-dev"
install:
- pip install pyflakes
- pip install docutils
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install pygments
script:
- private/run-pyflakes
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || find -name '*.rst' | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null
- make -C doc

# vim:ts=2 sts=2 sw=2 et
