dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
matrix:
  allow_failures:
  - python: "3.7-dev"
addons:
  apt:
    packages:
    - libydpdict2
cache: pip
install:
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install lxml
- pip install pydiatra pyflakes
- pip install docutils
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install pygments
script:
- private/run-pydiatra
- private/run-pyflakes
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || private/check-rst
- make -C doc
- make install PREFIX=~/.local
- export PATH=~/.local/bin:"$PATH"
- command -v ydpy
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || ydpy --help
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 ydpy | grep -A 10 -w YDPY

# vim:ts=2 sts=2 sw=2 et
