dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
install:
- pip install pyflakes
- pip install docutils
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install pygments
script:
- private/run-pyflakes
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || private/check-rst
- make -C doc

# vim:ts=2 sts=2 sw=2 et
